version: "3"

services:
  haproxy:
    image: mrcide/haproxy:1.8
    ports:
      - "8080:8080"
    volumes:
      - "${PWD}/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
  shiny:
    image: mrcide/shiny-server-base:3.5.1
