version: "3"

services:
  haproxy:
    image: mrcide/haproxy:latest

  shiny:
    image: mrcide/shiny-server-base:latest
    user: shiny
    volumes:
      - "applications:/shiny/apps"

  apache:
    depends_on:
      - haproxy
    image: httpd:2.4
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "${PWD}/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro"
      - "${PWD}/apache/auth:/usr/local/apache2/conf/auth:ro"
      - "${PWD}/apache/ssl:/usr/local/apache2/conf/ssl:ro"

volumes:
  applications:
