version: "3"

services:
  haproxy:
    image: mrcide/haproxy:1.8
    ports:
      - "8080:8080"
    volumes:
      - "${PWD}/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro"
  shiny:
    image: mrcide/shiny-server-base:3.5.1
  nginx:
    depends_on:
      - haproxy
    image: nginx:1.15
    ports:
      - "8081:8081"
    volumes:
      - "${PWD}/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
