server:
  address: "shiny.dide.ic.ac.uk"
  admin: "r.fitzjohn@imperial.ac.uk"

vault:
  address: "https://vault.dide.ic.ac.uk:8200"
  root: "/secret/shiny.dide"

apps:
  typochallenge:
    type: github
    spec: mrc-ide/typochallenge@auto_provision
    protect:
      - emails.db
      - contributions

  eppasmviewer:
    type: github
    spec: mrc-ide/eppasmviewer/inst/shiny/eppasmviewer@auto_provision
    auth:
      type: deploy_key
    groups:
      - dide-internal

  debug:
    type: local
    spec: shiny/applications/debug
    groups:
      - admin

  hello:
    type: local
    spec: shiny/applications/hello

  test:
    type: local
    spec: shiny/applications/test

groups:
  dide-internal:
    - rich
    - jeff
  admin:
    - admin
