apps:
  typochallenge:
    type: github
    spec: mrc-ide/typochallenge@auto_provision
    protect:
      - emails.db
      - contributions

  # debug:
  #   type: local
  #   spec: shiny/applications/debug
  #   # groups: admin

  hello:
    type: local
    spec: shiny/applications/hello

  test:
    type: local
    spec: shiny/applications/test
