twinkle_tag: {{{twinkle_version}}}

server:
  address: "shiny.example.com"
  admin: "you@example.com"
  port_http: 80
  port_https: 443
  # used for the self-signed certificate
  country: UK
  state: London
  organisation: Ministry of Silly Walks

# vault:
#   address: "https://vault.example.com:8200"
#   root: "/secret/shiny"

apps:
  hello:
    type: local
    spec: local/hello
